[[main]]
  name = "Docs"
  url = "/docs/"
  identifier = "docs"
  weight = 1

[[main]]
  name = "ML"
  url = "/docs/ml/intro/"
  identifier = "ml"
  parent = "docs"
  weight = 1

[[main]]
  name = "DL"
  url = "/docs/dl/intro/"
  identifier = "dl"
  parent = "docs"
  weight = 2

[[main]]
  name = "NLP"
  url = "/docs/nlp/intro/"
  identifier = "nlp"
  parent = "docs"
  weight = 3

# [[main]]
#   name = "DA"
#   url = "/docs/da/"
#   identifier = "da"
#   parent = "docs"
#   weight = 9

# [[main]]
#   name = "CV"
#   url = "/docs/cv/intro/"
#   identifier = "CV"
#   parent = "docs"
#   weight = 5

[[main]]
  name = "Misc"
  url = "/docs/misc/dsa/"
  identifier = "misc"
  parent = "docs"
  weight = 10

# [[main]]
#   name = "Multimodal"
#   url = "/docs/multi/intro/"
#   identifier = "multimodal"
#   parent = "docs"
#   weight = 3

# [[main]]
#   name = "blog"
#   url = "/blog/"
#   weight = 20

[[main]]
  name = "CV (pdf)"
  url = "https://drive.google.com/file/d/1oaiaBeoVIytQCwdp8UZ1guzi3D8vk1xq/view?usp=drive_link"
  weight = 20

[[main]]
  name = "Portfolio"
  url = "https://sites.google.com/view/renyiqu/portfolio"
  weight = 30

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/toastedqu?tab=repositories"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "LinkedIn"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-linkedin\"><path d=\"M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z\"/><rect x=\"2\" y=\"9\" width=\"4\" height=\"12\"/><circle cx=\"4\" cy=\"4\" r=\"2\"/></svg>"
  url = "https://www.linkedin.com/in/renyi-qu-6645a8150/"
  weight = 20

[[social]]
  name = "Email"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"1em\" viewBox=\"0 0 512 512\"><path d=\"M64 112c-8.8 0-16 7.2-16 16v22.1L220.5 291.7c20.7 17 50.4 17 71.1 0L464 150.1V128c0-8.8-7.2-16-16-16H64zM48 212.2V384c0 8.8 7.2 16 16 16H448c8.8 0 16-7.2 16-16V212.2L322 328.8c-38.4 31.5-93.7 31.5-132 0L48 212.2zM0 128C0 92.7 28.7 64 64 64H448c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128z\"/></svg>"
  url = "mailto: mikustokes@gmail.com"
  weight = 30

# [[main]]
#   name = "Help"
#   weight = 60
#   identifier = "help"
#   url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

# [[guide]]
#   name = "Lorem"
#   weight = 10
#   identifier = "lorem"
#   url = "/guide/lorem/"

# [[tutorial]]
#   name = "Lorem"
#   weight = 10
#   identifier = "lorem"
#   url = "/tutorial/lorem/"

# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

# [[main]]
#   name = "Get Started"
#   weight = 30
#   identifier = "get-started"
#   url = "/docs/prologue/introduction/"

# [[main]]
#   name = "Quick Start"
#   weight = 40
#   identifier = "quick-start"
#   url = "/docs/prologue/quick-start/"
#   parent = "get-started"

# [[main]]
#   name = "Tutorial"
#   weight = 50
#   identifier = "tutorial"
#   url = "https://getdoks.org/tutorial/introduction/"
#   parent = "get-started"



# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10


# [[main]]
#   name = "Models"
#   weight = 10
#   identifier = "models"
#   url = "/docs/ml/models/"
#   parent = "ml"

# [[main]]
#   name = "RL"
#   url = "/docs/ml/rl/"
#   identifier = "rl"
#   parent = "docs"
#   weight = 3